### ISSUE TITLE
Missing configuration regarding kernel modules

### ISSUE THREAD

**Issue by soppelmann** [BubbatheVTOG/2013-Pixel-ArchLinux#6]
Is there any steps left out in the install because the tpm modules and i915 dont appear loaded for me on kernel 5.2.8-arch1-1-ARCH.

I am running the original seabios with mr chromebox fix so in that sense I am keeping the original bios.

Also is there any configuration you did regarding the suspend and shutdown because my machine does a complete poweroff after a "systemctl suspend"

**Comment by soppelmann** [comment]
regarding suspend then there is a solution but ymmv
https://bbs.archlinux.org/viewtopic.php?id=176748
https://bugs.chromium.org/p/chromium/issues/detail?id=221905

`modprobe tpm_tis force=1 interrupts=0`
works for me

**Comment by BubbatheVTOG** [comment]
I sold my 2013 Pixel. I currently have the 2015 Pixel LS, which is a worthy upgrade if you can find a good condition one for a decent price (this is close to impossible though). 

I do remember having issues with suspend working and it was an issue with tpm. My fix was putting `tpm_tis.force=1 tpm_tis.interrupts=0` in the kernel params. I also had to change the behavior of the power button in `/etc/systemd/system/logind.conf`.

**Comment by soppelmann** [comment]
Ok!
I have been waiting for one on ebay for the better part of a year, wish me luck.

I also used modprobe for the i915 and tpm with good results.

Well, now its posted here for future readers. I put it in my rc.local, it wouldnt work for me as a grub param, think it had something to do with being a module but don't take my word for it!
